version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: firebase
    versions:
    - 8.2.1
    - 8.2.5
  - dependency-name: typeorm
    versions:
    - 0.2.29
    - 0.2.30
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: "@sentry/node"
    versions:
    - 5.29.2
    - 6.0.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: rxjs
    versions:
    - 6.6.3
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.7
