version: '3'

services:
    db:
      image: mysql:5.6
      ports:
        - 3306:3306
      environment:
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
