version: 2
jobs: 
  build:
    docker:
      - image: circleci/node:8.9.1
    
    working_directory: ~/repo

    steps: 
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "package.json" }}
      - run: yarn install
      - run: yarn prestart:prod
      - run: yarn test

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn