# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/ for more details
#
version: 2.1

executors:
  tabify-executor:
    docker:
      - image: circleci/node:10.19.0
    working_directory: ~/repo

jobs: 
  build:
    executor: tabify-executor
    steps: 
      - checkout
      - run:
          name: Install dependencies
          command: npm i # TODO: Change back to "npm ci" when node-gyp issue is resolved
      - run: npm run prestart:prod
      - run: npm run test

workflows:
  build-and-no-deploy:
    jobs:
      - build