version: 2
jobs: 
  build:
    docker:
      - image: circleci/node:8.9.1
    
    working_directory: ~/repo

    steps: 
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run: npm run prestart:prod
      - run: npm run test